image: node:20.17.0

before_script:
  - apt-get update -qq
  - apt-get install -qq git
  - "which ssh-agent || ( apt-get install -qq openssh-client )"
  - mkdir -p ~/.ssh
  - echo "$SSH_PRIVATE_KEY" > ~/.ssh/id_rsa
  - chmod 600 ~/.ssh/id_rsa
  - eval $(ssh-agent -s)
  - ssh-add ~/.ssh/id_rsa
  - echo -e "Host *\n\tStrictHostKeyChecking no\n" > ~/.ssh/config

deploy:
  stage: deploy
  environment:
    name: develop
    url: https://develop.off-market.lu
  script:
    - bash deploy/deploy.sh
  only:
    - develop

deploy_prod:
  stage: deploy
  environment:
    name: production
    url: https://www.off-market.lu
  script:
    - bash deploy_prod/deploy.sh
  only:
    - master
