// This file is auto-generated by next-intl, do not edit directly.
// See: https://next-intl.dev/docs/workflows/typescript#messages-arguments

declare const messages: {
  "Error": {
    "description": "<p>Nous avons malheureusement rencontré une erreur.</p><p>Vous pouvez essayer de <retry>recharger la page</retry> que vous consultiez.</p>",
    "title": "Quelque chose s'est mal passé !"
  },
  "IndexPage": {
    "description": "Ceci est un exemple de base qui démontre l'utilisation de <code>next-intl</code> avec le routeur App de Next.js. Essayez de changer la langue en haut à droite pour voir le contenu s'adapter.",
    "title": "Secretimmo"
  },
  "LocaleLayout": {
    "title": "Vente confidentielle de biens immobiliers d’exception au Luxembourg en off-market par Secretimmo",
    "description": "Vendez votre bien de prestige en toute discrétion en hors marché avec Secretimmo. Service confidentiel, réseau d'acheteurs qualifiés, estimation gratuite et rapide.",
    "ogTitle": "Vente confidentielle de biens immobiliers d'exception en off-market",
    "ogDescription": "Secretimmo est un service discret réservé aux propriétaires souhaitant vendre sans exposition grand publique.",
    "twitterTitle": "Vente immobilière discrète",
    "twitterDescription": "Service confidentiel dédié aux biens haut de gamme à vendre au Luxembourg.",
    "canonical" : "https://off-market.lu/"
  },
  "LocaleSwitcher": {
    "label": "Changer de langue",
    "locale": "{locale, select, de {🇩🇪 Deutsch} en {🇺🇸 English} other {Inconnu}}"
  },
  "Manifest": {
    "name": "Secretimmo"
  },
  "Navigation": {
    "home": "Accueil",
    "pathnames": "Chemins"
  },
  "NotFoundPage": {
    "description": "Veuillez vérifier l'adresse dans la barre de navigation ou utilisez le menu pour accéder à une page connue.",
    "title": "Page introuvable",
    "backToHome" : "Retour à l’accueil"
  },
  "PageLayout": {
    "links": {
      "docs": {
        "description": "En savoir plus sur next-intl dans la documentation officielle.",
        "href": "https://next-intl.dev",
        "title": "Documentation"
      },
      "source": {
        "description": "Parcourir le code source de cet exemple sur GitHub.",
        "href": "https://github.com/amannn/next-intl/tree/main/examples/example-app-router",
        "title": "Code source"
      }
    }
  },
  "PathnamesPage": {
    "description": "<p>Les chemins sont également internationalisés.</p><p>Si vous utilisez l’anglais par défaut, vous verrez <code>/en/pathnames</code> dans la barre d’adresse du navigateur sur cette page.</p><p>Si vous changez la langue en allemand, l’URL est localisée en conséquence (<code>/de/pfadnamen</code>).</p>",
    "title": "Chemins"
  },
  "Footer": {
    "company": "Société Anonyme au capital de 100.000€ - RCS B258313 - TVA LU33290343",
    "copyright": "2021-2025 © Secretimmo SA. Tous les droits sont réservés.",
    "designedBy": "Conçu par",
    "metaLink": "Meta.lu",
    "metaUrl": "https://www.meta.lu/fr",
    "partnerText": "& Partenaire Premium de",
    "nextimmoLink": "Nextimmo.lu",
    "nextimmoUrl": "https://nextimmo.lu/",
    "secretimmoLink": "Secretimmo.lu",
    "secretimmoUrl": "https://secretimmo.lu/",
    "goodworkLink": "Goodwork.lu", 
    "goodworkUrl": "https://goodwork.lu/fr"
  },
  "Header": {
    "header_1": "Un service confidentiel, réservé aux biens d’exception.",
    "header_2": "Réponse sous 24 h garantie."
  },
  "Form": {
    "title": "Check your property's eligibility",
    "desc": "Secretimmo’s private sales service is exclusively dedicated to luxury, distinctive, or high-value properties. <br />To check if your property meets our criteria, we invite you to take an eligibility test. <br />Your data is processed in strict confidence and is never shared without your consent.",
    "secretimmo_title": "✅ Congratulations, your property is considered an exceptional property and could be marketed off-market!",
    "secretimmo_desc": "Please fill out the valuation request form to know the current value of your property.",
    "nextimmo_subtitle": "❌ Your property is not considered an exceptional property and could not be marketed off-market!",
    "nextimmo_title": "The good news is that via Nextimmo, our on-market sales partner, you can sell it effectively.",
    "nextimmo_desc": "Please fill out the valuation request form to know the current value of your property.",
    "criteria_title": "Criteria",
    "locality_label": "Locality",
    "locality_placeholder": "Luxembourg",
    "type_label": "Type of property",
    "select_type": "Select a type",
    "propertyTypes": {
      "home": "House|Detached house|Mansion|Architect's house|Property|Listed building|Farmhouse",
      "appartement": "Apartment|Duplex|Triplex|Loft|Penthouse"
    },
    "surface_label": "Total surface",
    "rooms_label": "Number of rooms",
    "exterior_title": "Exterior",
    "garages_label": "Garages",
    "parkings_label": "Parkings",
    "garden_label": "Garden",
    "terrace_label": "Terraces/Balconies",
    "equipment_title": "Equipment",
    "piscine_label": "Swimming pool",
    "sports_area_label": "Sports area",
    "smart_home_label": "Home automation",
    "alarm_label": "Alarm",
    "spa_label" : "Spa",
    "terms_label": "By checking this box, you accept our <privacyLink>Privacy Policy</privacyLink>.",
    "privacyLinkUrl" : "https://secretimmo.lu/en/privacy",
    "submit_button": "Check eligibility",
    "secretimmo_button": "Request a Secretimmo evaluation",
    "nextimmo_button": "Request a Nextimmo evaluation",
    "first_name_label": "First name",
    "last_name_label": "Last name",
    "phone_label": "Phone number",
    "email_label": "E-mail",
    "first_name_error": "First name must be between 2 and 50 characters and contain only letters",
    "last_name_error": "Last name must be between 2 and 50 characters and contain only letters",
    "phone_error": "Invalid phone number",
    "email_error": "Invalid e-mail address",
    "submit_success": "Your request has been successfully sent.",
    "submit_error": "An error occurred while sending the form. Please try again.",
    "terms_error": "Please accept the terms.",
    "min_error": "The minimum value must be greater than or equal to ",
    "max_error": "he maximum value must be less than or equal to ",
    "type_error": "The value format is invalid.",
    "locality_error" : "The value format is invalid.",
    "required_error" : "This field is required."
  }
};
export default messages;